matrix:
  include:
    - language: scala
      jdk: oraclejdk8
      before_script: cd data-source-simulator
      script:
        - sbt compile
      after_script: cd ..
    - language: java
      jdk: oraclejdk8
      before_script: cd stormcassandrapulling 
      script:
        - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
        - mvn test -B
      after_script: cd ..
      
notifications:
  email: false